version: "3.9"
services:
  app:
    build: src
    image: pythonseqfinder:latest
  test:
    image: pythonseqfinder:latest
    volumes:
      - .:/app
    command: ["python","test_longestIncreasingSequence.py"]