name: build-sequence-app
on: [push]
jobs:
  lint-test-build:
    runs-on: ubuntu-latest
    steps:       
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
      - name: Lint code
        run: |
          pip install flake8
          flake8 .      
      - name: Unit test
        run: |
          python test_longestIncreasingSequence.py
